version: '3.8'                                                                                 
                                                                                               
services:                                                                                      
  db:                                                                                          
    image: mysql:5.7                                                                           
    container_name: db                                                                         
    platform: linux/x86_64                                                                     
    environment:                                                                               
      MYSQL_DATABASE: bookapi                                                                  
      MYSQL_USER: app                                                                          
      MYSQL_PASSWORD: password                                                                 
      MYSQL_ROOT_PASSWORD: root_password                                                       
    ports:                                                                                     
      - "3306:3306"                                                                            
    volumes:                                                                                   
      - db_data:/var/lib/mysql                                                                 
    networks:                                                                                  
      - app-network                                                                            
                                                                                               
                                                                                               
  api:                                                                                         
    build:                                                                                     
      context: ./api                                                                           
      dockerfile: Dockerfile                                                                   
    container_name: laravel_api                                                                
    ports:                                                                                     
      - "8000:8000"                                                                            
    depends_on:                                                                                
      - db                                                                                     
    networks:                                                                                  
      - app-network                                                                            
    volumes:                                                                                   
      - api_data:/var/www                                                                      
    env_file:                                                                                  
      - ./api/.env                                                                             
                                                                                               
  client:                                                                                      
    build:                                                                                     
      context: ./client                                                                        
      dockerfile: Dockerfile                                                                   
    container_name: nuxt_client                                                                
    ports:                                                                                     
      - "3000:3000"                                                                            
    environment:                                                                               
      VITE_API_URL: http://api:8000                                                            
    depends_on:                                                                                
      - api                                                                                    
    networks:                                                                                  
      - app-network                                                                            
                                                                                               
  nginx:                                                                                       
    image: nginx:alpine                                                                        
    container_name: nginx_proxy                                                                
    ports:                                                                                     
      - "80:80"                                                                                
      - "443:443"                                                                              
    volumes:                                                                                   
      - ./nginx.conf:/etc/nginx/nginx.conf                                                     
      - nginx_data:/usr/share/nginx/html                                                       
      - /etc/nginx/ssl:/etc/nginx/ssl  # Add this line to mount the SSL certificates           
    depends_on:                                                                                
      - client                                                                                 
      - api                                                                                    
    networks:                                                                                  
      - app-network                                                                            
                                                                                               
volumes:                                                                                       
  db_data:                                                                                     
  api_data:                                                                                    
  nginx_data:                                                                                  
                                                                                               
networks:                                                                                      
  app-network:                                                                                 